<a href="https://colab.research.google.com/github/faria012/Colab/blob/main/Numpy_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy = Numerical Python



In [ ]:
import numpy as np

List vs NumPy - Time taken

In [ ]:
from time import process_time

Time taken by a list

In [ ]:
python_list = [ i for i in range(10000)]

start_time = process_time()

python_list = [ i+5 for i in python_list]
end_time = process_time()

print(end_time - start_time)

0.0015108290000003244


In [ ]:
np_array = np.array( [i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.001720919000000265


NumPy Array

In [ ]:
list = [1,2,3,4,5]

print(list)
type(list)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
a.shape

(5,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

Initial Placeholder in numpy array

In [ ]:
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
b = np.random.random((3,4))
print(b)

[[0.60340661 0.49598117 0.44083143 0.91772291]
 [0.47932164 0.89336828 0.36219798 0.3412268 ]
 [0.1191241  0.94876391 0.86189794 0.04710727]]


In [ ]:
c = np.random.randint(10,100,(3,5))
print(c)

[[26 56 28 55 96]
 [41 60 30 91 33]
 [82 16 82 40 73]]


In [ ]:
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
list1 = [10,20,20,30,40]

np_array = np.asarray(list1)

print(np_array)
type(np_array)

[10 20 20 30 40]


numpy.ndarray

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[87 21 46 58 41]
 [82 10 75 23 20]
 [58 52 24 16 29]
 [19 55 27 69 10]
 [38 80 37 55 84]]


In [ ]:
print(c.shape)

(5, 5)


In [ ]:
print(c.ndim)

2


In [ ]:
print(c.size)

25


In [ ]:
print(c.dtype)

int64


Mathematical operations on a np array

In [ ]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]

print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)

[[4 7 1]
 [2 4 9]
 [3 7 8]]
[[12 12 14]
 [15 19 19]
 [18 14 11]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[16 19 15]
 [17 23 28]
 [21 21 19]]
[[ -8  -5 -13]
 [-13 -15 -10]
 [-15  -7  -3]]
[[ 48  84  14]
 [ 30  76 171]
 [ 54  98  88]]
[[0.33333333 0.58333333 0.07142857]
 [0.13333333 0.21052632 0.47368421]
 [0.16666667 0.5        0.72727273]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(np.add(a,b))

[[22 14 27]
 [11 16 11]
 [13 17 15]]


Array Manipulation

In [ ]:
import numpy as np
array = np.random.randint(0,10,(3,3))
print(array)
print(array.shape)

[[8 0 5]
 [0 4 7]
 [2 1 3]]
(3, 3)


In [ ]:
trans = np.transpose(array)

In [ ]:
print(trans)

[[8 0 2]
 [0 4 1]
 [5 7 3]]


In [ ]:
print(trans.shape)

(3, 3)


In [ ]:
array = np.random.randint(0,10,(2,3))

In [ ]:
print(array)

[[0 1 8]
 [6 1 4]]


In [ ]:
trans2 = np.transpose(array)

In [ ]:
print(trans2)

[[0 6]
 [1 1]
 [8 4]]
